author: TechMastary
database: false
description: Is chat going out of hand? Disable the use of global chat!
main: net.techmastary.plugins.chatmaster.ChatMaster
name: ChatMaster
startup: postworld
url: http://TechMastary.net/
version: '1.2.1'
commands:
  cm:
    description: ChatMaster base command.
    usage: /[command] <args>
  pping:
    description: Pings player.
    usage: /[command] <player>
  cmupdate:
    description: Update ChatMaster
    usage: /[command]
permissions:
